### ISSUE TITLE
Cannot find modules after upgrade to 1.1.3

### ISSUE THREAD

**Issue by bobum** [aurelia/validation#480]
**I'm submitting a bug report**

* **Library Version:**
1.1.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.22

* **Browser:**
Chrome 65.0.3325.181 (Official Build) (64-bit)

* **Language:**
ES6

**Current behavior:**
I got sucked into this project and know little about Aurelia, please forgive...about a week ago the application was rebuilt and since then it has stopped working.  I've tracked it down to this...

When trying to use v1.1.3 of the aurelia-validation library, when our app starts up we get the following behavior:

https://www.screencast.com/t/uvNbnwUA1sj4

I've enclosed the current working package.json - if I carrot the aurelia-validation dependency - the app breaks with the above error messages...

[package.zip](https://github.com/aurelia/validation/files/1852148/package.zip)

When I back it down and pin the version to 1.1.2 - all is well.

**Expected/desired behavior:**
I'd like to be able to stay up to date with the latest Aurelia versions
Any insight into what is misconfigured is greatly appreciated.

**Comment by Alexander-Taran** [comment]
You probably use npm and you have `package.lock.json`
Delete that file and node_modules and reinstall dependencies.

It is probably an npm issue

**Comment by Alexander-Taran** [comment]
how do you import plugin?

**Comment by bobum** [comment]
In code, a normal import statement like this:

`import {ValidationRules, ValidationController} from 'aurelia-validation';`

And in the package.json, like this:

`"aurelia-validation": "1.1.2"` <-- no errors

when we change to 

`"aurelia-validation": "1.1.3"` or `"aurelia-validation": "^1.1.2"` <-- we get the aurelia-loader-webpack cannot find validate-binding-behavior, validation-custom-attribute and validation-renderer-custom-attribute errors (https://www.screencast.com/t/zZHTrGV3D)

**Comment by jkesselring** [comment]
Seconding @bobum's findings. Has any work been done on this issue?

**Comment by bobum** [comment]
@jkesselring are you getting the exact same dependencies that can't be found as we are?

**Comment by jkesselring** [comment]
@bobum In so far as I have seen, yes.

**Comment by jdanyow** [comment]
Let me rollup some of the important details from the comments above and see if an aurelia+webpack expert can help out with this.  I would try updating `aurelia-loader-webpack` and any other aurelia packages to the latest versions for starters.

summary of user's issue:

> "aurelia-validation": "1.1.2" <-- no errors
>
>when we change to
>
>"aurelia-validation": "1.1.3" or "aurelia-validation": "^1.1.2" <-- we get the aurelia-loader-webpack cannot find validate-binding-behavior, validation-custom-attribute and validation-renderer-custom-attribute errors (https://www.screencast.com/t/zZHTrGV3D)

user's package.json:

<details>
  <summary>package.json</summary>
<pre><code>
  {
  "name": "ipsadmin-lights-map",
  "version": "2.0.0",
  "description": "Aurelia and webpack based lights map, powered by leaflet.",
  "scripts": {
    "start": "webpack-dev-server --config webpack.config.js --watch --content-base src",
    "starts": "webpack-dev-server --config webpack.config.js --watch --content-base src --https",
    "start:dev": "npm start -- --inline",
    "start:dev:hot": "npm run start:dev -- --hot",
    "build": "webpack --config ./webpack.config.js",
    "build:production": "webpack --config ./webpack.prod.config.js",
    "build:dev": "SET NODE_ENV=develop && npm run build",
    "build:qa": "SET NODE_ENV=qa && npm run build",
    "build:prod": "SET NODE_ENV=production && npm run build:production",
    "build:ext": "SET NODE_ENV=external && npm run build"
  },
  "license": "ISC",
  "devDependencies": {
    "aurelia-webpack-plugin": "^1.1.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-async-to-generator": "^6.22.0",
    "babel-plugin-transform-class-properties": "^6.22.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-rest-spread": "^6.22.0",
    "babel-preset-babili": "0.0.12",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-es2015-loose-native-modules": "^1.0.0",
    "babel-preset-es2017": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-preset-stage-2": "^6.18.0",
    "babel-register": "^6.11.6",
    "babili-webpack-plugin": "0.0.11",
    "copy-webpack-plugin": "^4.0.0",
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.22.0",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "raw-loader": "^0.5.1",
    "style-loader": "^0.13.1",
    "webpack": "2.1.0-beta.22",
    "webpack-dev-server": "2.1.0-beta.0"
  },
  "dependencies": {
    "aurelia-bootstrapper-webpack": "^1.0.0",
    "aurelia-event-aggregator": "^1.0.0",
    "aurelia-fetch-client": "^1.0.0",
    "aurelia-framework": "^1.0.0",
    "aurelia-history-browser": "^1.0.0",
    "aurelia-http-client": "^1.0.2",
    "aurelia-loader-webpack": "^1.0.0",
    "aurelia-logging-console": "^1.0.0",
    "aurelia-pal-browser": "^1.0.0",
    "aurelia-polyfills": "^1.0.0",
    "aurelia-route-recognizer": "^1.0.0",
    "aurelia-router": "^1.0.2",
    "aurelia-templating-binding": "^1.0.0",
    "aurelia-templating-resources": "^1.0.0",
    "aurelia-templating-router": "^1.0.0",
    "aurelia-validation": "1.1.2",
    "bluebird": "^3.4.1",
    "json-loader": "^0.5.4",
    "leaflet": "1.0.1",
    "leaflet-draw": "0.4.9",
    "leaflet-path-drag": "1.0.1",
    "whatwg-fetch": "^2.0.2"
  }
}
</code></pre>
</details>
</br>

confirmation that aurelia-validation uses `PLATFORM.moduleName`:

https://github.com/aurelia/validation/blob/e74ca868f97780283dfa186207587e3e4c0a1482/src/aurelia-validation.ts#L78-L85
