### ISSUE TITLE
Expression 'command.InternalNotes&validate' is not compatible with the validate binding-behavior.

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia/validation#350]
Hi,

I'm new to this library, using the latest version (both of aurelia framework & validation). My configuration is skeleton navigation typescript with webpack.

My class is configured as following:

```
import { autoinject, newInstance } from 'aurelia-framework';
import { OrderService } from '../order-service';
import { Router } from 'aurelia-router';
import { ValidationController, ValidationRules  } from 'aurelia-validation';
import { BootstrapFormRenderer  } from '../../resources/validation/bootstrap-form-renderer';

@autoinject
export class OrderSetInternalNotes {

    heading: string = 'Set internal notes';
    command: any = null;

    constructor(private orderService: OrderService,
                private router: Router,
                @newInstance(ValidationController) private validationController: ValidationController) {

        this.validationController.addRenderer(new BootstrapFormRenderer());

    }

    activate(params) {
        this.orderService.getSetInternalNotes(params.id, params.timestamp).then(getSetInternalNotesResponse => {
            if (!getSetInternalNotesResponse.Meta.Success) {
                this.cancel();
            }
            this.command = getSetInternalNotesResponse.Results[0];
            ValidationRules
                .ensure('InternalNotes').required().maxLength(5)
                .on(this.command);
        });
    }

    async execute() {
        let errors = await this.validationController.validate();
        if (errors.length > 0){
            return;
        }
        let getSetInternalNotesResponse = await this.orderService.setInternalNotes(this.command);
        if (!getSetInternalNotesResponse.Meta.Success) {
            return;
        }
        this.close();
    }

    cancel() {
        this.close();
    }

    private close() {
        this.router.navigateToRoute('orderList');
    }

}
```

the object "command" is gathered from the server and then I'd like to attach the validation when ready.

here is the html

```
<template>

  <section class="au-animate">
    <h2>${heading}</h2>
    <form role="form" submit.delegate="execute()">
      <div class="form-group">
        <label for="internalNotes">Intenal notes</label>
        <textarea class="form-control"
                  rows="12"
                  value.bind="command.InternalNotes & validate"
                  id="internalNotes"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Ok</button>
      <button click.delegate="cancel()" class="btn btn-default">Cancel</button>
    </form>
  </section>
  
</template>
```

Am I doing something wrong?

Thanks for any advice!
Enrico

**Comment by jdanyow** [comment]
what's the stack trace

**Comment by enrico-padovani** [comment]
[Here](https://github.com/aurelia/validation/files/497904/localhost-1475062717248.zip) you can find the chrome stack trace. Unfortunately returning the promise does not solve the problem.

**Comment by valichek** [comment]
I have the same issue, but with javascript/webpack, trying to upgrade from old validation (0.6.7) to the latest (0.13)

```javascript
import {computedFrom, NewInstance} from 'aurelia-framework';
import {ValidationController, ValidationRules} from 'aurelia-validation';
import {BootstrapFormRenderer} from 'lib/validation/bootstrap-form-renderer';
class LoginData {
  
  username = '';
  password = '';
  
}

ValidationRules
  .ensure(a => a.username).required().minLength(3).email()
  .ensure(a => a.password).required()
  .on(LoginData);

export class Login {
  
  static inject() { return [NewInstance.of(ValidationController)]; }
  
  constructor(validationController) {
    let login = new LoginData();
    this.login = login;
    
    this.validationController = validationController;
    this.validationController.addRenderer(new BootstrapFormRenderer());
    
  }
  
  activate(params) {
    
    console.log('Login', 'activate', params);
    
  }
  
  deactivate() {
    
    console.log('Login', 'deactivate');
    
  }
  
  submit(){
    
    this.validationController.validate();
    
  }
  
}

```

```html
<template>
<form>
<fieldset>

<div class="form-group block clearfix">
   <label t="form.email"></label>
   <span class="block input-icon input-icon-right">
     <input type="email" class="form-control" t="[placeholder]form.email" value.bind="login.username & validate"/><i class="ace-icon fa fa-user"></i>
   </span>
</div>

<div class="form-group block clearfix">
  <label t="form.password"></label>
  <span class="block input-icon input-icon-right">
    <input type="password" class="form-control" placeholder="Password" value.bind="login.password & validate"/><i class="ace-icon fa fa-lock"></i>
  </span>
</div>

</fieldset>
</form>
</template>
```

```
Error: Expression 'login.username&validate' is not compatible with the validate binding-behavior.
Stack trace:
Error: Expression 'login.username&validate' is not compatible with the validate binding-behavior.
    getPropertyInfo@http://localhost:3000/1.bundle.js:61632:16
    ValidationController</ValidationController.prototype.resetBinding@http://localhost:3000/1.bundle.js:61561:19
    ValidateBindingBehaviorBase</ValidateBindingBehaviorBase.prototype.bind/binding.updateTarget@http://localhost:3000/1.bundle.js:61237:18
    bind@http://localhost:3000/1.bundle.js:26675:6
    bind@http://localhost:3000/1.bundle.js:18591:8
    bind@http://localhost:3000/1.bundle.js:20563:8
    automate@http://localhost:3000/1.bundle.js:20508:6
    swap@http://localhost:3000/1.bundle.js:72452:6
    _commitChanges/</<@http://localhost:3000/1.bundle.js:13896:17
    _commitChanges/<@http://localhost:3000/1.bundle.js:13895:8
From previous event:
    _commitChanges@http://localhost:3000/1.bundle.js:13894:13
    run@http://localhost:3000/1.bundle.js:13743:13
    next@http://localhost:3000/1.bundle.js:13712:19
    iterate@http://localhost:3000/1.bundle.js:14798:13
    inspect@http://localhost:3000/1.bundle.js:14769:15
    iterate/_ret3</<.v<@http://localhost:3000/1.bundle.js:14787:23
    processPotential@http://localhost:3000/1.bundle.js:14915:13
    iterate/_ret3<@http://localhost:3000/1.bundle.js:14786:17
    iterate@http://localhost:3000/1.bundle.js:14780:22
    processActivatable@http://localhost:3000/1.bundle.js:14801:11
    run@http://localhost:3000/1.bundle.js:14682:13
    next@http://localhost:3000/1.bundle.js:13712:19
    iterate@http://localhost:3000/1.bundle.js:14711:13
    processDeactivatable@http://localhost:3000/1.bundle.js:14714:11
    run@http://localhost:3000/1.bundle.js:14670:13
    next@http://localhost:3000/1.bundle.js:13712:19
    iterate@http://localhost:3000/1.bundle.js:14798:13
    processActivatable@http://localhost:3000/1.bundle.js:14801:11
    run@http://localhost:3000/1.bundle.js:14658:13
    next@http://localhost:3000/1.bundle.js:13712:19
    run@http://localhost:3000/1.bundle.js:58380:13
From previous event:
    run@http://localhost:3000/1.bundle.js:14945:13
    next@http://localhost:3000/1.bundle.js:13712:19
    iterate@http://localhost:3000/1.bundle.js:14711:13
    processDeactivatable@http://localhost:3000/1.bundle.js:14714:11
    run@http://localhost:3000/1.bundle.js:14646:13
    next@http://localhost:3000/1.bundle.js:13712:19
    run/<@http://localhost:3000/1.bundle.js:14148:15
From previous event:
    run@http://localhost:3000/1.bundle.js:14146:13
    next@http://localhost:3000/1.bundle.js:13712:19
    run@http://localhost:3000/1.bundle.js:13725:13
    _dequeueInstruction/<@http://localhost:3000/1.bundle.js:15274:15
From previous event:
    _dequeueInstruction@http://localhost:3000/1.bundle.js:15247:13
    activate@http://localhost:3000/1.bundle.js:15224:6
    registerViewPort/_ret6</_ret7</<.v.v<@http://localhost:3000/1.bundle.js:15194:22
From previous event:
    registerViewPort/_ret6</_ret7<@http://localhost:3000/1.bundle.js:15191:23
    registerViewPort/_ret6<@http://localhost:3000/1.bundle.js:15186:26
    registerViewPort@http://localhost:3000/1.bundle.js:15182:20
    RouterView@http://localhost:3000/1.bundle.js:72355:6
    invokeWithDynamicDependencies@http://localhost:3000/1.bundle.js:16434:11
    invoke@http://localhost:3000/1.bundle.js:16416:154
    invoke@http://localhost:3000/1.bundle.js:16678:15
    get@http://localhost:3000/1.bundle.js:19181:63
    get@http://localhost:3000/1.bundle.js:16615:13
    elementContainerGet@http://localhost:3000/1.bundle.js:19236:11
    create@http://localhost:3000/1.bundle.js:21166:47
    applyInstructions@http://localhost:3000/1.bundle.js:19330:19
    create@http://localhost:3000/1.bundle.js:19551:8
    create@http://localhost:3000/1.bundle.js:21178:28
    createController/<@http://localhost:3000/1.bundle.js:21600:15
From previous event:
    createController@http://localhost:3000/1.bundle.js:21586:13
    _createControllerAndSwap@http://localhost:3000/1.bundle.js:21565:13
    compose@http://localhost:3000/1.bundle.js:21645:15
    compose@http://localhost:3000/1.bundle.js:21909:13
    setRoot@http://localhost:3000/1.bundle.js:48467:13
    [216]/</<@http://localhost:3000/bundle.js:8410:13
From previous event:
    [216]/<@http://localhost:3000/bundle.js:8409:4
    bootstrap/<@http://localhost:3000/bundle.js:18482:13
    onBootstrap/</<@http://localhost:3000/bundle.js:18411:20
    run/</<@http://localhost:3000/bundle.js:18472:10
From previous event:
    run/<@http://localhost:3000/bundle.js:18464:6
From previous event:
    run@http://localhost:3000/bundle.js:18459:11
    [224]/<@http://localhost:3000/bundle.js:18486:2
    [224]@http://localhost:3000/bundle.js:18387:30
    __webpack_require__@http://localhost:3000/bundle.js:583:12
    hotCreateRequire/fn@http://localhost:3000/bundle.js:107:20
    [216]@http://localhost:3000/bundle.js:8318:36
    __webpack_require__@http://localhost:3000/bundle.js:583:12
    hotCreateRequire/fn@http://localhost:3000/bundle.js:107:20
    [0]@http://localhost:3000/bundle.js:639:2
    __webpack_require__@http://localhost:3000/bundle.js:583:12
    @http://localhost:3000/bundle.js:629:18
    @http://localhost:3000/bundle.js:1:11
```

**Comment by valichek** [comment]
I did some debug, so here is result
```
// code from getPropertyInfo()
while (expression instanceof BindingBehavior || expression instanceof ValueConverter) {
    expression = expression.expression; // never goes here
  }
```

so `expression` is always same as `originalExpression `

expression object looks like:

![ddcd05dda00c334b54d778fcf77fc74f](https://cloud.githubusercontent.com/assets/7127622/19015694/c01703ee-8811-11e6-97ce-048bd8aeb498.png)

**Comment by valichek** [comment]
@enrico-padovani so, I have fixed this issue, this worked for me:
```
npm uninstall aurelia-validation --save
npm install aurelia-binding --save
npm install aurelia-validation --save
```

**Comment by enrico-padovani** [comment]
Nope,

after updating aurelia-validation to 0.13.0 I get [this](https://github.com/aurelia/validation/files/505668/localhost-1475478145900.zip) error.

"Unhandled rejection TypeError: this.bindinqLanguage.parseInterpolation is not a function"

**Comment by valichek** [comment]
@enrico-padovani I would suggest you to clear node_modules first and  re-install

**Comment by enrico-padovani** [comment]
npm mysteries ... now It's working as expected. I think it was related to version 0.12.0.

Thanks!

**Comment by migajek** [comment]
I got the same issue. Reinstalling doesnt help. Any ideas?

**Comment by Alexander-Taran** [comment]
@migajek what makes you think it is the same?
Please provide your setup as per issue template.
Better yet, create a new issue with a reference to this one

**Comment by Alexander-Taran** [comment]
@jdanyow for review

**Comment by avrahamcool** [comment]
I also face this error in a code that was working in version `1.1.2`.
didn't modify anything in the code - just updating `aurelia-validation` from `1.1.2` to `1.1.3` causes the error.

I have a rather complex scenario, where I construct my `validationController` manually.
using `controllerFactory.create()` instead of `controllerFactory.createForCurrentScope()`.
and then. in the view I bind the input to the `validationController` manually:

`<input type="text" value.bind="orderModel.OrderId & validate:orderModel.validationController" /></label>`

![image](https://user-images.githubusercontent.com/5445320/37654010-60d6d156-2c49-11e8-9613-810f5220ea1d.png)

**Comment by samueldjack** [comment]
I've just encountered this issue too with aurelia-validation 1.1.3. I've just upgraded to Webpack 4, and along with that updated all my other aurelia dependencies. So it's a little tricky to tell exactly what is the problem.

I tried uninstalling and reinstalling aurelia-validation 1.1.3 but that didn't help. Neither did trashing my node_modules directory and doing npm install again.

In the end I had to revert to aurelia-validation 1.1.2 which works fine.

**Comment by samueldjack** [comment]
I think I've just found the problem: an out-of-date reference to aurelia-binding. In fact I didn't have an explicit reference to it in package.json.

I've just explicitly installed aurelia-binding 1.7.1 and now aurelia-validation 1.1.3 is working for me.

@avrahamcool Does this work for you too?

**Comment by Alexander-Taran** [comment]
@samueldjack what package manager do you use?
npm or yarn?
and what version
If there is project.lock.json in your project folder?

**Comment by avrahamcool** [comment]
@samueldjack 
yes - updating `aurelia-binding` to `1.7.1` fixed the issue for me too.
[I also didn't have an explicit dependency on it]
thanks.

**Comment by Alexander-Taran** [comment]
@samueldjack & @avrahamcool 
ok.. Seems like underlying issue is not eager updating of non direct dependencies
yet https://github.com/aurelia/validation/blob/875b9251b08980fa3425e26e5de5923db0866c39/package.json#L82
clearly states that it need 1.7.1  or higher of binding

do you have a git point in time before upgrade?
I'd love to experiment on that.

**Comment by samueldjack** [comment]
I'm using npm, and I upgraded by doing `npm install aurelia-validation@1.1.3`

Unfortunately I don' have a public git repo for this.

**Comment by avrahamcool** [comment]
I also don't have a public git for that,
but I'll try to recreate the issue in a clean project.

**Comment by Alexander-Taran** [comment]
I'd take a zip of clone.. If not commercial sercet (-:

**Comment by avrahamcool** [comment]
I'm working on it now.
I'm striping everything except the problem - so it'll be easier to reproduce.

**Comment by avrahamcool** [comment]
I'm unable to recreate the problem.

earlier in my tests - I already had a `node_modules` folder that was created when I first created the project  - and I just deleted the `package.lock` before each installation.
I didn't delete the `node_modules` folder because I only wanted to update the `aurelia-validation`.

apparently that was the problem.
FYI:
I created the project using NPM 5.6.0 - and now I tried to update using NPM 5.7.1

@samueldjack can you confirm this in your project also?

**Comment by pkozul** [comment]
Does anyone have this working with`aurelia-binding 2.0.0`? I updated to `aurelia-binding 2.0.0` and now I am getting this error.

Tried deleting the `node_modules` folder, uninstalling and reinstalling `aurelia-binding` and` aurelia-validation`, deleting `package-lock.json`, etc. but still no luck.

For now, I have reverted to `aurelia-binding 1.7.1` which works OK.

**Comment by Alexander-Taran** [comment]
@pkozul npm? what version?

**Comment by ralbu** [comment]
I get the same error. Below is my setup. It looks like some dependencies/versions are broken with webpack (and maybe not only webpack)
Created new project from the command line. Webpacka and TypeScript were selected
```
npm install aurelia-binding --save
npm install aurelia-validation --save
```
Added the validation plugin in the main.js file:
```
  aurelia.use
    .standardConfiguration()
    .feature(PLATFORM.moduleName('resources/index'))
    .plugin(PLATFORM.moduleName('aurelia-validation'));
```
Added the validation functionality in the App files (the file which was created by default)
```
import {autoinject} from 'aurelia-framework';
import { ValidationController, ValidationControllerFactory, ValidationRules } from 'aurelia-validation';

@autoinject()
export class App {
  private controller: ValidationController;

  constructor(controllerFactory: ValidationControllerFactory) {
    this.controller = controllerFactory.createForCurrentScope();
    ValidationRules
      .ensure('title').required()
      .on(this);
  }
}

<template>
  <input type="text" placeholder="Title" value.bind="title & validate" required>
</template>
```
This are the package dependencies:

    "aurelia-animator-css": "^1.0.2",
    "aurelia-binding": "^2.0.0",
    "aurelia-bootstrapper": "^2.1.1",
    "aurelia-polyfills": "latest",
    "aurelia-validation": "^1.1.3",
    "bluebird": "^3.4.1"
    


When I run it this is the error:
```
Unhandled rejection Error: Expression 'title&validate' is not compatible with the validate binding-behavior.
    at getPropertyInfo (webpack-internal:///40:37:15)
    at ValidationController.resetBinding (webpack-internal:///13:368:107)
    at Binding.binding.updateTarget (webpack-internal:///58:60:43)
    at Binding.bind (webpack-internal:///49:5033:12)
    at View.bind (webpack-internal:///1:1479:19)
    at Controller.bind (webpack-internal:///1:3492:17)
    at Controller.automate (webpack-internal:///1:3437:10)
    at eval (webpack-internal:///1:4581:18)
From previous event:
    at CompositionEngine._createControllerAndSwap (webpack-internal:///1:4580:43)
    at CompositionEngine.compose (webpack-internal:///1:4666:19)
    at TemplatingEngine.compose (webpack-internal:///1:4930:36)
    at Aurelia.setRoot (webpack-internal:///aurelia-framework:131:19)
    at eval (webpack-internal:///main:27:55)
From previous event:
    at Object.configure (webpack-internal:///main:27:21)
    at eval (webpack-internal:///65:129:27)
From previous event:
    at config (webpack-internal:///65:124:54)
    at eval (webpack-internal:///65:160:12)
From previous event:
    at bootstrap (webpack-internal:///65:159:24)
    at eval (webpack-internal:///65:146:7)
From previous event:
    at run (webpack-internal:///65:141:59)
    at Object.eval (webpack-internal:///65:166:16)
    at eval (webpack-internal:///65:167:30)
    at Object.65 (http://localhost:8080/app.31705b096a6d00c808ee.bundle.js:565:1)
    at __webpack_require__ (http://localhost:8080/app.31705b096a6d00c808ee.bundle.js:20:30)
    at Object.48 (http://localhost:8080/app.31705b096a6d00c808ee.bundle.js:413:18)
    at __webpack_require__ (http://localhost:8080/app.31705b096a6d00c808ee.bundle.js:20:30)
    at http://localhost:8080/app.31705b096a6d00c808ee.bundle.js:63:18
    at http://localhost:8080/app.31705b096a6d00c808ee.bundle.js:66:10
```

**Comment by elmt1** [comment]
I am also running into this issue after upgrading to aurelia-binding 2.0.0 while upgrading to webpack 4. I downgraded to 1.7.1, deleted my node_modules folder and package-lock.json and reran npm install. I am still getting the same error.  Using webpack 4.8.3, npm 6.0.1 various version of aurelia-binding. When I have a little more time, I will bring up a working version and see what is different in the way it checks to see if expression as an instance of AccessMember.

**Comment by elmt1** [comment]
I am not sure if this is helpful but I ran a working version next to a failing version and I see some differences in what ValidateController passes to getPropertyInfo.

Working version: expression.constructor.name -- returns "AccessMember"

Non-working version: 
expression.constructor.name -- returns "BindingBehavior"
I can see expression.expression.constructor.name is "AccessMember"

As an experiment I changed getPropertyInfo in the failing version look for expression.expression and at a high level validation seems to work. It could probably have used expression.expression instanceof but this was just a proof of concept. Of course, I have don't really know how it is supposed to be working but maybe this helps figure out the root cause of this error.

export function getPropertyInfo(expression, source) {
    var originalExpression = expression;
    while (expression instanceof BindingBehavior || expression instanceof ValueConverter) {
        expression = expression.expression;
    }
    var object;
    var propertyName;
    if (expression instanceof AccessScope) {
        object = getContextFor(expression.name, source, expression.ancestor);
        propertyName = expression.name;
    **} else if (expression.expression.constructor.name === "AccessScope") {
        object = getContextFor(expression.expression.name, source, expression.expression.ancestor);
        propertyName = expression.expression.name;**
    } else if (expression instanceof AccessMember) {
        object = getObject(originalExpression, expression.object, source);
        propertyName = expression.name;
    **} else if (expression.expression.constructor.name === "AccessMember") {
        object = getObject(originalExpression.expression, expression.expression.object, source);
        propertyName = expression.expression.name;**
    } else if (expression instanceof AccessKeyed) {
        object = getObject(originalExpression, expression.object, source);
        propertyName = expression.key.evaluate(source);
    **} else if (expression.expression.constructor.name === "AccessKeyed") {
        object = getObject(originalExpression.expression, expression.expression.object, source);
        propertyName = expression.expression.key.evaluate(source);**
    } else {
        throw new Error("Expression '" + originalExpression + "' is not compatible with the validate binding-behavior.");
    }
    if (object === null || object === undefined) {
        return null;
    }
    return { object: object, propertyName: propertyName };
}

**Comment by bigopon** [comment]
@fkleuver bringing this to your attention

**Comment by fkleuver** [comment]
Yep, was able to reproduce this. It goes wrong here:

```js
while (expression instanceof BindingBehavior || expression instanceof ValueConverter) {
  expression = expression.expression;
}
```

An expression of type `BindingBehavior` comes in but `expression instanceof BindingBehavior` evaluates to false.

It appears that 1.7.1 is stored in the lockfile as a redirect from `^1.0.0` and 2.0.0 is stored as a separate entry. The Aurelia libraries depending on `aurelia-binding` all get their own reference to 1.7.1.

So you get this effect:

`aurelia-binding@^2.0.0`
![image](https://user-images.githubusercontent.com/9655331/40581542-d7e11bfc-615b-11e8-9f5e-b834b967519f.png)

`aurelia-binding@^1.7.1`
![image](https://user-images.githubusercontent.com/9655331/40581546-04f80c22-615c-11e8-9028-2e22234e4b3f.png)

`aurelia-binding@^1.7.1`
![image](https://user-images.githubusercontent.com/9655331/40581585-f8c635a4-615c-11e8-98a6-949a47c50ef5.png)

`aurelia-templating-binding` loads its own version to parse the expressions, `aurelia-validation` also loads its own version to compare the constructors. They're both 1.7.1 (2.0.0 isn't even loaded) but different instances, so the constructor functions don't match up.

1.7.1 being loaded doesn't really surprise me though - that's semantic versioning doing its job. I guess the dependency on `aurelia-binding` needs to be changed to "^1.0.0 | ^2.0.0".

What does baffle me is that each library loads its own unique instance, even of the same version. At the very least should the same 1.7.1 instance be reused so this sort of thing doesn't happen. I'd argue that's a webpack issue, but I'm not entirely sure.

**Comment by elmt1** [comment]
Based on what you found, I started looking at why I might have duplicate copies of aurelia-binding running. I think I found another symptom. For some reason it was bundled in both the app.js and vendor.js bundles. According to the Aurelia documentation [Duplicate Bundles in Multiple Bundles](https://aurelia.io/#duplicate-modules-in-multiple-bundles) is a bad thing.  

Once again, I reverted to aurelia-binding 1.71 and this time I ran npm dedupe without deleting my package.lock file. I didn't expect this to help but now I am not seeing aurelia-binding in my app.js bundle.  Everything seems to work and all unit tests now pass.  In addition, this cleared up a problem with duplicate lines being rendered in a repeat.for. 

At this point, it is just luck that things are working. I think it would be a good idea to read and understand the section in the Aurelia Webpack documentation -- "To have full control over how Webpack distributes and de-duplicates the modules in the chunks, please refer to Webpack documentation on the matter and replace the @easy-webpack/config-common-chunks-simple configuration with a custom one."
