### ISSUE TITLE
1.3.0 Breaks Custom Element Validation

### ISSUE THREAD

**Issue by LilSebastian5000** [aurelia/validation#516]
**I'm submitting a bug report**

* **Library Version:**
1.3.0 and 1.3.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.0

* **NPM Version:**
5.8.0

* **JSPM OR Webpack AND Version**
webpack 4.28.2

* **Browser:**
Chrome / All

* **Language:**
ESNext

**Current behavior:**
When upgrading from 1.2.3 to 1.3.0, validation on custom elements no longer work and prevent a page from loading. The following error presents itself:
<pre>VM1101 aurelia-logging-console.js:50 ERROR [app-router] Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
    at validateKey (aurelia-dependency-injection.js:414)
    at Container.get (aurelia-dependency-injection.js:618)
    at Container.elementContainerGet [as get] (VM1086 aurelia-templating.js:2393)
    at getTargetDOMElement (aurelia-validation.js:63)
    at ValidateOnChangeOrBlurBindingBehavior.ValidateBindingBehaviorBase.bind (aurelia-validation.js:704)
    at BindingBehavior.bind (VM1087 aurelia-binding.js:1258)
    at Binding.bind (VM1087 aurelia-binding.js:5042)
    at Controller.bind (VM1086 aurelia-templating.js:3763)
    at View.bind (VM1086 aurelia-templating.js:1745)
    at Controller.bind (VM1086 aurelia-templating.js:3785)
    at Controller.automate (VM1086 aurelia-templating.js:3730)
    at ready (VM1145 router-view.js:168)
    at RouterView.swap (VM1145 router-view.js:197)
    at eval (aurelia-router.js:285)
    at Array.forEach (<anonymous>)
    at eval (aurelia-router.js:284)
    at tryCatcher (VM980 bluebird.js:4954)
    at Promise._settlePromiseFromHandler (VM980 bluebird.js:3095)
    at Promise._settlePromise (VM980 bluebird.js:3152)
    at Promise._settlePromise0 (VM980 bluebird.js:3197)
    at Promise._settlePromises (VM980 bluebird.js:3277)
    at Promise._fulfill (VM980 bluebird.js:3221)</pre>

When debugging in Chrome, it appears that when the code enters getTargetDOMElement in `aurelia-validation.js` after finding the target custom element, an exception is thrown on this line: 
` var element = controller.container.get(aurelia_pal__WEBPACK_IMPORTED_MODULE_0__["DOM"].Element);`

Example html markup:
`<drop-down-field element-id="custom-drop-down" name="customDropDown"
                                 value.bind="customDropDownValue & validateOnChangeOrBlur:customRules.someRule"></drop-down-field>`

Snippet from drop-down-field JS:
<pre>
...
@inject(Element)
export class DropDownField {
  @bindable({defaultBindingMode: bindingMode.twoWay}) value = '';

  constructor(element) {
    this.element = element;
  }
...</pre>

**Expected/desired behavior:**

* **What is the expected behavior?**
Validation should be fired on my custom drop down field. It should highlight in red when invalid, or green when valid. Instead, the page won't even load and provides an error in the console.

* **What is the motivation / use case for changing the behavior?**
This worked previously in versions 1.0.0 through 1.2.3. I was working to migrate to Webpack 4 and the latest Aurelia dependencies when encountering this. Version 1.2.3 of Aurelia Validation is as high as I can go before breaking my application.

Note: I also tried only updating aurelia and leaving Webpack at version 3.10.0 like I had been using previously, so it seems unrelated to upgrading Webpack.

**Updated:** I was able to get this working. It appears that "aurelia-framework" has quite a few outdated aurelia dependencies that we hadn't called out in our package.json previously.

I have now added the latest versions of "aurelia-loader", "aurelia-logging", "aurelia-router", "aurelia-metadata", and "aurelia-pal", and validation is now working.

**Comment by bigopon** [comment]
Unless `Element` in the above code block is from `DOM`, it should work.

This is a typical issue with combination of webpack, commonjs and DI. Because `DOM.Element` reference is used to early, before platform initialization populates the value of `DOM.Element` with proper reference so it injects `undefined` into DropdownField. Maybe you are referencing some modules too early that it triggers module evaluation before platform initialization starts.

**Comment by LilSebastian5000** [comment]
> Unless `Element` in the above code block is from `DOM`, it should work.
> 
> This is a typical issue with combination of webpack, commonjs and DI. Because `DOM.Element` reference is used to early, before platform initialization populates the value of `DOM.Element` with proper reference so it injects `undefined` into DropdownField. Maybe you are referencing some modules too early that it triggers module evaluation before platform initialization starts.

Hmm, will look into this, thanks. So, something in 1.3 broke this? I noticed that the getTargetDOMElement method that my code is failing on was new in that release. 

The weird thing is, though.. getTargetDOMElement does find the dropdown field if I set a breakpoint on it. It prints me the entire drop-down html element. It just get's that error on the "controller.container.get"

**Comment by LilSebastian5000** [comment]
> Unless `Element` in the above code block is from `DOM`, it should work.
> 
> This is a typical issue with combination of webpack, commonjs and DI. Because `DOM.Element` reference is used to early, before platform initialization populates the value of `DOM.Element` with proper reference so it injects `undefined` into DropdownField. Maybe you are referencing some modules too early that it triggers module evaluation before platform initialization starts.

It looks like "Element" comes from "lib.dom.d.ts", what should this be coming from?

**Comment by bigopon** [comment]
@LilSebastian5000 I meant the real value of `Element` at runtime, not at design phase in TypeScript.

**Comment by bigopon** [comment]
@LilSebastian5000 It's a bit confusing. Can you just use `Element` instead of `DOM.Element`?

**Comment by LilSebastian5000** [comment]
@bigopon How can I do that? From what dependency?

As shown in my snippet, Element is what I'm using inside `@inject(Element)`, not `@inject(DOM.Element)`

I found this link which seems like it may help, but it returns a 404: https://aurelia.io/docs/templating/html-behaviors-introduction/#getting-the-dom-element-for-your-behavior

**Comment by bigopon** [comment]
Do you have `containerless` on your `DropdownField`?

**Comment by LilSebastian5000** [comment]
> Do you have `containerless` on your `DropdownField`?

Hey there! As shown in my snippet, I was not using containerless. I did try using @containerless with @inject(Element), as well as @containerless with @customElement('drop-down-field') and none of these combinations resolve the issue.

**Comment by LilSebastian5000** [comment]
Updated: I was able to get this working. It appears that "aurelia-framework" has quite a few outdated aurelia dependencies that we hadn't called out in our package.json previously. 

I have now added the latest versions of "aurelia-loader", "aurelia-logging", "aurelia-router", "aurelia-metadata", and "aurelia-pal", and validation is now working.

**Comment by LilSebastian5000** [comment]
> Oh well, that's unexpected. Glad you have it worked and guess we can close this? @LilSebastian5000

Yep, all set, thanks!
